version: '3.8'
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mnist:/opt/mount
      - ./data:/workspace/data
    command: python train.py --save-dir /opt/mount

  evaluate:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mnist:/opt/mount
      - ./data:/workspace/data
    command: python eval.py --save-dir /opt/mount

  infer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mnist:/opt/mount
    command: python infer.py

volumes:
  mnist:
